" ---------------------------------------------------
" Must have options
set nocompatible
set hidden
syntax on
colorscheme vividchalk

" load filetype specific indent files in .vim/ftplugin
filetype plugin indent on

" visual autocomplete when tabbing in command mode
set wildmenu

" show last command in Vim
set showcmd


" ---------------------------------------------------
" Usability options

" case insensitive search
set ignorecase
set smartcase

" search as chars are entered
set incsearch
" highlight matches
set hlsearch

set autoindent

" allow backspacing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start

" stop certain movements from always going to first char of line
set nostartofline

" diplay cursor position in bottom of screen
set ruler

" always display status line
set laststatus=2

" instead of failing on unsaved changes, ask pls
set confirm

" no more beeping
set visualbell
set t_vb=

" enable use of mouse for all modes
set mouse=a

" set command window height to 2 lines
set cmdheight=2

" line numbers
set number

" quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200

" use <F11> to toggle between 'paste' and 'nopaste', allowing pasting
" without setting indenting wrong
set pastetoggle=<F11>


" ---------------------------------------------------
" Indentation options

" use 4 spaces instead of tabs
set shiftwidth=4
set softtabstop=4
set expandtab


" ---------------------------------------------------
" Mappings

" move vertically by visual line
nnoremap j gj
nnoremap k gk

" remap move to beginning/end of line
nnoremap B ^

" map Y to yank until EOL
map Y y$
nnoremap E $

" turn off search highlight with ,<space> cmd
nnoremap ,<space> :nohlsearch<CR>
